services:
  monitor-bot:
    build: .
    container_name: monitor-bot
    restart: unless-stopped
    network_mode: host
    pid: host
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    # docker ps/compose
      - /usr/bin/docker:/usr/local/bin/docker:ro     # docker CLI
      - /usr/libexec/docker/cli-plugins:/usr/local/libexec/docker/cli-plugins:ro  # compose plugin
      - /sys:/sys:ro                                  # CPU temp
      - /proc:/host_proc:ro                           # proses host
      - /:/host_root:ro                               # disk host
      - /home/fixt1r:/home/fixt1r:ro                  # akses project files
